version: '3.9'
services:
    postgres:
        image: postgres:14.1
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - /home/darksied/dev/pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

