version: '3.9'
services:
    db:
        image: postgres:14.1
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - /db/dbdata:/var/lib/postgresql/data
    web:
      build: .
      depends_on:
        - db
      volumes:
        - .:/app/
      env_file:
        - '.env.dev'
      ports:
        - '3001:3001'

volumes:
  dbdata:

