apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: env-dev
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PASSWORD
                  name: env-dev
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_USERNAME
                  name: env-dev
            - name: FIRST_RUN
              valueFrom:
                configMapKeyRef:
                  key: FIRST_RUN
                  name: env-dev
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  key: RAILS_ENV
                  name: env-dev
            - name: RAZORPAY_API
              valueFrom:
                configMapKeyRef:
                  key: RAZORPAY_API
                  name: env-dev
            - name: RAZORPAY_SECRET
              valueFrom:
                configMapKeyRef:
                  key: RAZORPAY_SECRET
                  name: env-dev
            - name: SEED
              valueFrom:
                configMapKeyRef:
                  key: SEED
                  name: env-dev
          image: web
          name: web
          ports:
            - containerPort: 3001
          resources: {}
          volumeMounts:
            - mountPath: /app/
              name: web-claim0
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
status: {}
